# Generated by Django 6.1 on 2026-08-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tamano', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=5)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
